-- Customers Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    GENDER VARCHAR(10),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    JOIN_DATE DATE
);

-- Products Table
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    PRICE DECIMAL(10,2)
);

-- Orders Table
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    ORDER_DATE DATE,
    QUANTITY INT,
    TOTAL_AMOUNT DECIMAL(10,2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- Payments Table
CREATE TABLE PAYMENTS (
    PAYMENT_ID INT PRIMARY KEY,
    ORDER_ID INT,
    PAYMENT_METHOD VARCHAR(30),
    PAYMENT_STATUS VARCHAR(20),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
