-- 1. View all customers
SELECT * FROM CUSTOMERS;

-- 2. View all products
SELECT * FROM PRODUCTS;

-- 3. Top 5 expensive products
SELECT *
FROM PRODUCTS
ORDER BY PRICE DESC
LIMIT 5;

-- 4. Total revenue
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS;

-- 5. Total orders
SELECT COUNT(*) AS TOTAL_ORDERS
FROM ORDERS;

-- 6. Average order value
SELECT AVG(TOTAL_AMOUNT)
FROM ORDERS;

-- 7. City-wise customers
SELECT CITY,COUNT(*)
FROM CUSTOMERS
GROUP BY CITY;

-- 8. Category-wise products
SELECT CATEGORY,COUNT(*)
FROM PRODUCTS
GROUP BY CATEGORY;

-- 9. Customer Order Details
SELECT
C.CUSTOMER_NAME,
P.PRODUCT_NAME,
O.QUANTITY,
O.TOTAL_AMOUNT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN PRODUCTS P
ON O.PRODUCT_ID=P.PRODUCT_ID;

-- 10. Highest Order Value
SELECT *
FROM ORDERS
ORDER BY TOTAL_AMOUNT DESC
LIMIT 1;
