-- INNER JOIN
SELECT
C.CUSTOMER_NAME,
P.PRODUCT_NAME,
O.QUANTITY,
O.TOTAL_AMOUNT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID;

-- LEFT JOIN
SELECT
C.CUSTOMER_NAME,
O.ORDER_ID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID;

-- RIGHT JOIN
SELECT
P.PRODUCT_NAME,
O.ORDER_ID
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID;
