-- ROW_NUMBER
SELECT
CUSTOMER_ID,
TOTAL_AMOUNT,
ROW_NUMBER() OVER(ORDER BY TOTAL_AMOUNT DESC) AS RN
FROM ORDERS;

-- RANK
SELECT
CUSTOMER_ID,
TOTAL_AMOUNT,
RANK() OVER(ORDER BY TOTAL_AMOUNT DESC) AS RANK_NO
FROM ORDERS;

-- DENSE_RANK
SELECT
CUSTOMER_ID,
TOTAL_AMOUNT,
DENSE_RANK() OVER(ORDER BY TOTAL_AMOUNT DESC) AS DR
FROM ORDERS;

-- Department style example using customer
SELECT
CUSTOMER_ID,
TOTAL_AMOUNT,
ROW_NUMBER() OVER(
PARTITION BY CUSTOMER_ID
ORDER BY TOTAL_AMOUNT DESC
) AS RN
FROM ORDERS;
