-- 1. Top 5 Customers by Revenue

SELECT
C.CUSTOMER_NAME,
SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 5;


-- 2. Monthly Sales Trend

SELECT
MONTH(ORDER_DATE) AS MONTH,
SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM ORDERS
GROUP BY MONTH
ORDER BY MONTH;


-- 3. Best Selling Products

SELECT
P.PRODUCT_NAME,
SUM(O.QUANTITY) AS TOTAL_SOLD
FROM PRODUCTS P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SOLD DESC;

-- 4. Customer Order Frequency

SELECT
CUSTOMER_ID,
COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_ORDERS DESC;

-- 5. Total Revenue Generated

SELECT
SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS;

-- 6. Average Order Value

SELECT
AVG(TOTAL_AMOUNT) AS AVERAGE_ORDER_VALUE
FROM ORDERS;

-- 7. Product Category Performance

SELECT
P.CATEGORY,
SUM(O.TOTAL_AMOUNT) AS CATEGORY_REVENUE
FROM PRODUCTS P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY CATEGORY_REVENUE DESC;
